openapi: 3.0.1
info:
  title: API de agencia de viajes MoonTravels.
  description: Esta API se encarga de manejar la informacion de la empresa MoonTravels.
  version: 1.0.0
servers:
- url: https://github.com/Gabo2447/discord_js
tags:
- name: clientes
  description: Maneja informacion de los clientes de MoonTravels